---
name: "Release"

on:
  push:
    paths-ignore:
      - '**/README.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      
    branches:
      - "master"
      - "develop"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/exec
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
